name: Terraform Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    name: Validate Terraform Syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: install localstacks
        run: pip install --upgrade localstack

      - name: export auth token
        run: export LOCALSTACK_AUTH_TOKEN="ls-lobifEKi-xIwa-KefA-3555-bEFo66139c56"

      - name: Configure AWS credentials (for LocalStack)
        run: |
          export AWS_ACCESS_KEY_ID="test"
          export AWS_SECRET_ACCESS_KEY="test"
          export AWS_DEFAULT_REGION="sa-east-1"

      - name: start local LocalStack
        run: |
          localstack start &
          echo "Terraform Validate"
          make apply component=vpc env=dev

      - name: Terraform Validate
        run: make validate component=vpc env=dev
