name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform-validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup LocalStack
        run: pip install terraform-local

      # - name: tflocal validate vpc
      #   run: make validate component=vpc env=dev
      
      - name: ls
        run: ls -la pwd
